@startuml you-look-familiar
title password syncing (used in account linking)
participant Client
participant Ping_DaVinci
participant Evernote
Ping_DaVinci->Client: Redirect to username/pwd for user to enter credentials\nto authorize account linking for SIWA
Client->Ping_DaVinci: Enters credentials and redirects back to Ping_DaVinci
alt  credentials matches with Ping user
    note right of Ping_DaVinci: i.e; user is already migrated to Ping
else credentials do not match
    Ping_DaVinci->Evernote: check for user in Evernote
    alt if credentials matches with Evernote user
        Evernote->Ping_DaVinci: success with user details
    else
        Evernote->Ping_DaVinci: Don't allow login!
    end
end
@enduml