@startuml you-look-familiar
title SIWA of an existing Evernote user (i.e; either linked or not linked to user name/pwd account)
actor Actor as User
participant Client
participant Ping_DaVinci
participant Evernote
User->Client: Initiates SIWA
Client->Ping_DaVinci: SIWA OIDC flow
Ping_DaVinci->Apple: redirects to apple IDP
Apple->Client: apple prompts for the user to sign-in
Client->Apple: user signs in and authorizes EN for SIWA
Apple->Ping_DaVinci: user is authenticated (openId and email)
Ping_DaVinci->Evernote: how to proceed (existing account/need linking/registration/error)?
Evernote->Ping_DaVinci: User already exists - returns Evernote user id
Ping_DaVinci->Evernote: get custom claims for user id
Evernote->Ping_DaVinci: returns custom claims
Ping_DaVinci->Client: successful and gives access token (JWT)
@enduml